name: Blackjack
version: 2.4.0
main: com.vortex.blackjack.BlackjackPlugin
description: A physical blackjack table game for Minecraft
api-version: 1.21
depend: [Vault]
softdepend: [GSit, PlaceholderAPI]
loadbefore: []
load: POSTWORLD

authors: [DefectiveVortex, LittleBigBug]

commands:
  blackjack:
    description: Main command for the Blackjack plugin
    usage: |
      &8[&6Blackjack&8] &rAvailable Commands:
      &e/bj createtable &7- Create a new blackjack table
      &e/bj removetable &7- Remove the nearest table
      &e/bj join &7- Join the nearest table
      &e/bj leave &7- Leave your current table
      &e/bj start &7- Start a new game
      &e/bj hit &7- Take another card
      &e/bj stand &7- End your turn
      &e/bj doubledown &7- Double your bet and take exactly one more card
      &e/bj bet <amount> &7- Place or change your bet
      &e/bj stats [player] &7- View statistics
    aliases: [bj]

permissions:
  blackjack.admin:
    description: Allows creation and removal of blackjack tables
    default: op
  blackjack.play:
    description: Allows playing blackjack
    default: true
  blackjack.stats.others:
    description: Allows checking other players' statistics
    default: op